// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriVie.Models.Data;

#nullable disable

namespace NutriVie.Migrations
{
    [DbContext(typeof(NutriVieDbContext))]
    [Migration("20260924173918_NutriVieService01")]
    partial class NutriVieService01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriVie.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NomService")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Des recettes équilibrées et faciles à préparer pour toute la famille.",
                            NomService = "Recettes Saines"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Des plans alimentaires personnalisés par nos nutritionnistes.",
                            NomService = "Plans Nutritionnels"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Des articles et guides sur la nutrition et le bien-être.",
                            NomService = "Conseils d'Experts"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
