// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriVie.Models.Data;

#nullable disable

namespace NutriVie.Migrations
{
    [DbContext(typeof(NutriVieDbContext))]
    [Migration("20260924173212_NutriVie01")]
    partial class NutriVie01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriVie.Models.Aliment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CaloriesPour100g")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aliments");
                });

            modelBuilder.Entity("NutriVie.Models.AlimentRecette", b =>
                {
                    b.Property<int>("RecetteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetteId"));

                    b.Property<int>("AlimentId")
                        .HasColumnType("int");

                    b.Property<double>("Poids")
                        .HasColumnType("float");

                    b.Property<int>("RecetteId1")
                        .HasColumnType("int");

                    b.HasKey("RecetteId");

                    b.HasIndex("AlimentId");

                    b.HasIndex("RecetteId1");

                    b.ToTable("AlimentRecettes");
                });

            modelBuilder.Entity("NutriVie.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NutriVie.Models.Recette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlimentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempsCuisson")
                        .HasColumnType("int");

                    b.Property<int>("TempsPreparation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlimentId");

                    b.ToTable("Recettes");
                });

            modelBuilder.Entity("NutriVie.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NomService")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Des recettes équilibrées et faciles à préparer pour toute la famille.",
                            NomService = "Recettes Saines"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Des plans alimentaires personnalisés par nos nutritionnistes.",
                            NomService = "Plans Nutritionnels"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Des articles et guides sur la nutrition et le bien-être.",
                            NomService = "Conseils d'Experts"
                        });
                });

            modelBuilder.Entity("NutriVie.Models.AlimentRecette", b =>
                {
                    b.HasOne("NutriVie.Models.Aliment", "Aliment")
                        .WithMany()
                        .HasForeignKey("AlimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriVie.Models.Recette", "Recette")
                        .WithMany()
                        .HasForeignKey("RecetteId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aliment");

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("NutriVie.Models.Recette", b =>
                {
                    b.HasOne("NutriVie.Models.Aliment", null)
                        .WithMany("Recettes")
                        .HasForeignKey("AlimentId");
                });

            modelBuilder.Entity("NutriVie.Models.Aliment", b =>
                {
                    b.Navigation("Recettes");
                });
#pragma warning restore 612, 618
        }
    }
}
